### ISSUE TITLE
Fix Test Failed

### ISSUE THREAD

**Issue by yjaeseok** [lunchclass/bacardi#212]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites
* [x] Are you running the latest version?

### Description
[Description of the bug or feature]
When I download latest version 
I got some error when I test bacardi project
commitId : d523d7acbf5226c1d9f211f1d80ff76cfa1fb642

### Steps to Reproduce
```shell
$ git clone https://github.com/lunchclass/bacardi.git
$ cd bacardi
$ git checkout d523d7acbf5226c1d9f211f1d80ff76cfa1fb642
$ ./bacardi test
```

**Expected behavior:** [What you expect to happen]
All test pass

**Actual behavior:** [What actually happens]
One test case failed with below logs:
 FAIL  test/interface_constructor.test.ts failed: Symbol not found: __ZN19TestInterfaceBridge4InitEN4Napi3EnvENS0_6ObjectE
  ● Test suite failed to run

    ProcessTerminatedError: cancel after 2 retries!

      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:87:25)
          at Array.forEach (<anonymous>)
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:81:36)
      at ontimeout (timers.js:475:11)
      at tryOnTimeout (timers.js:310:5)
      at Timer.listOnTimeout (timers.js:270:5)

A worker process has quit unexpectedly! Most likely this is an initialization error.

### Operating System
* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)

**Comment by yjaeseok** [comment]
This is human error!
